version: '2.1'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    # ports:
    #   - 9001:9001
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=myminiokeythatishouldchange123"
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set clipable http://minio:9000 minio myminiokeythatishouldchange123;
      /usr/bin/mc mb clipable/clips;
      exit 0;
      "

  clippable:
    image: ghcr.io/clipable/clipable:latest
    environment:
      - DEBUG=true
      - LISTENADDR=:8080
      - FFMPEG_CONCURRENCY=1 # How many concurrent ffmpeg processes to run
      - FFMPEG_THREADS=0 # How many threads to use for a single ffmpeg process to use
      - FFMPEG_PRESET=medium # How much time to spend compressing https://trac.ffmpeg.org/wiki/Encode/H.264#:~:text=preset%20and%20tune-,Preset,-A%20preset%20is
      - FFMPEG_TUNE=film # https://trac.ffmpeg.org/wiki/Encode/H.264#:~:text=x264%20%2D%2Dfullhelp.-,Tune,-You%20can%20optionally
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_IDHASHKEY=mydbidkeythatishouldchange123
      - COOKIE_KEY=mycookiekey12345 # must be 16, 24, or 32 bytes long (AES-128, AES-192, or AES-256)
      - COOKIE_DOMAIN=localhost
      - S3_BUCKET=clips
      - S3_ACCESS=minio
      - S3_SECRET=myminiokeythatishouldchange123
      - S3_ADDRESS=minio:9000
    ports:
      - 80:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: {}
  minio_data: {}