name: Publish Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest frontend image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: frontend 
          docker-image-tag: latest # optional
          dockerfile-path: ./frontend/Dockerfile # optional
          build-context: ./frontend # optional
          build-only: false # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest backend image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: backend
          docker-image-tag: latest # optional
          dockerfile-path: ./backend/Dockerfile # optional
          build-context: ./backend # optional
          build-only: false # optional